language: python
python:
  - "3.5"
  - "3.6"

cache:
  - pip

install:
  - pip install -r requirements-test.txt
  - pip install codecov
  - python setup.py install

script:
  - py.test tests -s --cov

after_success:
  - codecov
